AllCops:
  TargetRubyVersion: '2.7.0'
  NewCops: enable
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
