#!/bin/bash

if_darwin()
{
  [[ "$(uname)" =~ 'Darwin' ]]
}

if_wsl()
{
  [[ "$(uname -r)" =~ 'Microsoft' ]]
}

if_ArchLinux()
{
  [[ $(sed -rn 's|^ID=(.+)$|\1|p' /etc/os-release) =~ ^arch ]]
}

if_openSUSE()
{
  [[ $(sed -rn 's|^ID="(.+)"$|\1|p' /etc/os-release) =~ ^opensuse ]]
}

cd "$HOME"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:71e6fd52/dotfile.git"

echo "Init submodules"
yadm submodule update --recursive --init

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"
  nvim '+PlugUpdate' '+qall'
fi

echo "get zsh plugin"
if if_ArchLinux
then
  : # TODO
else
  git clone https://github.com/bhilburn/powerlevel9k.git ~/opt/zsh-theme-powerlevel9k
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/opt/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/opt/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-completions.git ~/opt/zsh-completions
fi

if if_wsl
then
  echo "Turn to wsldm"
  yes | yadm --yadm-repo $HOME/.yadm_wsl clone git@github.com:71e6fd52/wsl-dotfile.git
fi
