#!/bin/bash

cd "$HOME"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:71e6fd52/dotfile.git"

echo "Init submodules"
yadm submodule update --recursive --init

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"
  nvim '+PlugUpdate' '+qall'
fi
