#!/bin/zsh

if_darwin()
{
  [[ "$(uname)" =~ 'Darwin' ]]
}

if_wsl()
{
  [[ "$(uname -r)" =~ 'Microsoft' ]]
}

if_ArchLinux()
{
  [[ $(sed -rn 's|^ID=(.+)$|\1|p' /etc/os-release) =~ ^arch ]]
}

if_openSUSE()
{
  [[ $(sed -rn 's|^ID="(.+)"$|\1|p' /etc/os-release) =~ ^opensuse ]]
}

cd "$HOME"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:71e6fd52/dotfile.git"

echo "Decrypt data"
yadm decrypt

echo "Init submodules"
yadm submodule update --recursive --init

if if_ArchLinux
then
  echo "Install Package"
  readonly packages=(
    moreutils exa bat fd ripgrep sd axel unarchiver openssh pass
    neovim python-neovim tmux
    rustup ruby python
  )
  sudo pacman -S --needed $packages
  sudo pacman -D --asexplicit $packages
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"
  nvim '+PlugUpdate' '+qall'
fi

if command -v rustup >/dev/null 2>&1; then
  echo "Install rust"
  rustup default nightly
  rustup update

  mkdir -p ~/.zfunc
  rustup completions zsh cargo > ~/.zfunc/_cargo
fi


echo "get zsh plugin"
if if_ArchLinux
then
  sudo pacman -S --needed zsh-theme-powerlevel9k zsh-syntax-highlighting zsh-autosuggestions zsh-completions
else
  git clone https://github.com/bhilburn/powerlevel9k.git ~/opt/zsh-theme-powerlevel9k
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/opt/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/opt/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-completions.git ~/opt/zsh-completions
fi

echo "clone password"
git clone git@github.com:71e6fd52/password.git ~/.password-store

if if_wsl
then
  echo "Turn to wsldm"
  yes | yadm --yadm-dir $HOME/.wsldm clone git@github.com:71e6fd52/wsl-dotfile.git
else
  echo "Please follow https://wiki.archlinux.org/index.php/Security to hardening system"
fi
